---

- hosts: all
  become: true
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes    
      when: ansible_distribution == "Ubuntu"

    - name: Install Apache2 web server package
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Ensure Apache is running and enabled
      service:
        name: apache2
        state: started
        enabled: true
      when: ansible_distribution == "Ubuntu"

    - name: Update openssh-client
      apt:
        name: openssh-client
        state: latest 
      when: ansible_distribution == "Ubuntu"

    - name: Add php support
      apt:
        name: libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Update dnf package index
      dnf:
        update_cache: yes    
      when: ansible_distribution == "CentOS"

    - name: Install Apache2 web server package
      dnf:
        name: httpd
        state: latest
      when: ansible_distribution == "CentOS"